### ISSUE TITLE
Tried to extract SBP from God of War PC

### ISSUE THREAD

**Issue by St0RM53** [secaproject/SBP_tool#1]
```
File/folder: C:\Users\TnF\Desktop\godofwar-test\spb\vo_glb_kratos_banter.sbp
C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - /C: (Errno::EINVAL)
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Users/TnF/AppData/Local/Temp/ocr96B.tmp/bin/sbp.rb:183:in `<main>'
```

Not sure if it's compatible or i am using it wrong, can you please help me with this?

Kind regards

**Comment by secaproject** [comment]
No, isn't compatible, but I can take a look at it if you send me the file.

**Comment by St0RM53** [comment]
Sure here's a small one you can have a look: https://www.dropbox.com/s/pzjwz8sxjjzz4og/vo_glb_baldur_banter.sbp?dl=0

**Comment by St0RM53** [comment]
Hey man, sorry to bother but did you have a look? Kind regards

**Comment by zhuyujun515** [comment]
Hello!Guys!I am also trying to extract SBP from God of War PC and have the same issues. If there is anything more, I would me very glad! Please!!!!!

**Comment by secaproject** [comment]
Sorry, I'll take a look today. In any case, this tool was made for MGSV, but I'll support other games.

**Comment by secaproject** [comment]
SBP from GoW seem to have an additional header, as if it were a container in which the SBP file itself is located. Could one of you send me more files? You can do it through the Discord channel.

**Comment by JaglacMax** [comment]
Hello, if you need I can send you more SBP files, just tell me where. If you still feel like helping.

I am trying to do a mod but cant figure it out.

**Comment by ehsanmousavizare** [comment]
Hi . Is there any SBP file extractor that work for God of War pc?

**Comment by secaproject** [comment]
I'm able to support it if any of you are able to share more files, otherwise I can't do anything.

**Comment by ehsanmousavizare** [comment]
Sure
https://uupload.ir/view/sbp_god_of_war_x1ba.zip/
https://drive.google.com/file/d/1KGaqc2KebVlEBUuFDzRdZDN0sfrkSc1J/view?usp=sharing
